### ISSUE TITLE
Once compiled, the mod won't actually do anything

### ISSUE THREAD

**Issue by Filo97** [qouteall/ImmersivePortalsModForForge#1]
![image](https://user-images.githubusercontent.com/15868262/69737169-34cc5780-1134-11ea-9381-f56a16c6a23a.png)
![image](https://user-images.githubusercontent.com/15868262/69737231-53325300-1134-11ea-8478-561e2a389f86.png)
![image](https://user-images.githubusercontent.com/15868262/69737286-70672180-1134-11ea-852d-7e225f9c0fd1.png)
![image](https://user-images.githubusercontent.com/15868262/69737317-78bf5c80-1134-11ea-959e-8b3db6bd767c.png)

**Comment by qouteall** [comment]
It works only in development environment now. That's why I haven't released the forge version. This mod relies on Mixin. Forge 1.13 uses the new modlauncher which is incompatible with Mixin. Mixin 0.8 is compatible with modlauncher now but the old way of embedding mixin into mod does not work under the new modlauncher. So forge have to ship with Mixin to let it work. Currently @cpw is in working on it. I will release the forge version when it's ready.

**Comment by Filo97** [comment]
By development enviornment, you mean with gradle runClient? Because it happens there, too.

**Comment by qouteall** [comment]
I run it by clicking the debug button on intellij idea. Do you see anything related to "mixin" in the log while running it?

**Comment by Filo97** [comment]
![image](https://user-images.githubusercontent.com/15868262/69899239-ab02d100-1363-11ea-9634-5b4af7c16921.png)
absolutely nothing related to mixin 
![image](https://user-images.githubusercontent.com/15868262/69899267-0df46800-1364-11ea-88d7-7ed11e671df0.png)

**Comment by Shazuli** [comment]
Yeah I'm having the same issue. First tried running it in console with `runClient`, when it didn't load mixin I opened in in the editor and ran it there, same result. Both time mixin wasn't mentioned in the console.

**Comment by qouteall** [comment]
I don't know what caused this. Maybe try to reimport the gradle?

**Comment by qouteall** [comment]
I just found that I didn't include manifest.mf in git. Try it again and it should be working.

**Comment by Filo97** [comment]
Yep, now works! 
![image](https://user-images.githubusercontent.com/15868262/70324794-b9079480-1830-11ea-9fe4-88d4e3b0a873.png)
