### ISSUE TITLE
Moving in and out of a portal can move you to other side

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#10]
Moving rapidly between dimensions with a portal can cause the player to exit on the wrong side. 

[Video demonstration](https://www.youtube.com/watch?v=rmuUSGBzl48)

**Comment by qouteall** [comment]
Probably fixed. You will see it in the next version

**Comment by qouteall** [comment]
oh new bugs occured

**Comment by qouteall** [comment]
check the newest version

**Comment by davidthehat** [comment]
Fixed
