### ISSUE TITLE
Incompatible with NetherGen+

### ISSUE THREAD

**Issue by getBoolean** [qouteall/ImmersivePortalsModForForge#101]
Immersive Portal's dimension stack feature doesn't work with NetherGen+.

1. The portal still gets placed at y=127 even though NetherGen+ allows you to change the Nether's height.

2. The Nether ceiling is made of bedrock instead of obsidian. This might be NetherGen+'s fault.

**Comment by LoganDark** [comment]
1. This is an issue with NetherGen+, since Immersive Portals uses World.getEffectiveHeight(). Tell them to patch it for the nether.
2. Not actually an issue with NetherGen+. We're just failing to replace it properly. This also happens in the overworld with TerraForged.

**Comment by getBoolean** [comment]
I sent a dm to the developer of NetherGen+ this on CurseForge since he does not have an issues page linked.

**Comment by ghost** [comment]
Patched this on my end:

https://www.curseforge.com/minecraft/mc-mods/nethergenplus/files/2962765

Src/Issues link is now on curseforge aswell

**Comment by LoganDark** [comment]
@Voronoiii Thank you, that was the correct solution :D

Edit: I looked at the source, and this actually probably _miight_ also need to be patched by Immersive Portals - they are the one changing from bedrock to obsidian, not you... But it works :P

**Comment by ghost** [comment]
Oh I have a custom bedrock placer here: https://github.com/Voronoiii/NetherGen-Plus/blob/94168f72bc0d70bd32e7bbb3ae7fc4582cd70c65/src/main/java/spore/nethergenplus/world/simplex/SimplexNetherGenerator.java#L91 and in the perlin equivalent.

But yeah it works :P

**Comment by LoganDark** [comment]
IP is the one converting it to obsidian, so maybe IP should be the one injecting into your methods and modifying them to return obsidian. But, yeah it works.
