### ISSUE TITLE
Crash on launch with OptiFine

### ISSUE THREAD

**Issue by ZekerZhayard** [qouteall/ImmersivePortalsModForForge#104]
Mod list:
forge-1.14.4-28.2.16
MixinBoostrap-1.0.3
immersive-portals-0.15 (for mc 1.14 with forge)
OptiFine_1.14.4_HD_U_F5
OptiForge_MC1.14.4_0.1.1

logs: https://paste.ubuntu.com/p/Zpvw55X93n/

**Comment by qouteall** [comment]
Firstly 1.14 is no longer supported. And the reentrance issue is caused by modlauncher and forge eventbus which is probably fixed in the latest version of forge 1.15

**Comment by ZekerZhayard** [comment]
OK, that's all
