### ISSUE TITLE
Block break/place lag spikes 1.15.2

### ISSUE THREAD

**Issue by deadspidervenom** [qouteall/ImmersivePortalsModForForge#105]
So i have no error log, but i made a modpack for my friends and while playing i get unbearable lag spikes when breaking or placing, last night after getting tired of it i went through all 141 mods one by one adding a mod, loading up, playing, shutting down, add mod.

Every time i added immersive portals in whether at 10 mods or 139 mods i would go from no issues to lag.

I can give my debug log, but i have no crash reports, and other people dont seem to be getting the same issues.

**Comment by qouteall** [comment]
Maybe it's correlated to the new model data fix

**Comment by qouteall** [comment]
Can confirm that the lag spike exists

**Comment by qouteall** [comment]
Fixed in 0.19
