### ISSUE TITLE
Using a high fov causes artifacts on edge of screen when moving between dimensions

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#11]
To replicate, set fov to quake pro and stand at the boundary between dimensions inside a portal. Player should be able to see artifacts on edge of screen.
![portalsBug](https://user-images.githubusercontent.com/24359213/72223361-e1736480-353b-11ea-88db-15b88ff35bb9.png)

**Comment by qouteall** [comment]
If you go to spectator mode and approach a wall closely you will see similar things. This is the inert defect of rasterization and cannot be fixed.

**Comment by qouteall** [comment]
I can increase the hood size but this issue will still show up if you use a even bigger fov.

**Comment by qouteall** [comment]
Do you usually play the game in maxium fov?

**Comment by davidthehat** [comment]
Yes, I play with quake pro normally which allowed me to notice the issue. I
have run into the issues you describe before, but those usually only appear
when a fov much higher than the maximum is set.

**Comment by qouteall** [comment]
fixed. you will see it in the next version.
But the issue still exists if you drink high level speed potion with quake pro fov

**Comment by qouteall** [comment]
check the newest version

**Comment by davidthehat** [comment]
Fixed
