### ISSUE TITLE
[1.15.2] Incapability of Depth Format Conversion

### ISSUE THREAD

**Issue by Jarfeh** [qouteall/ImmersivePortalsModForForge#110]
Hey there, I'm currently trying to use shaders with the immersive portals mod, and whenever I do, it switches over to compatibility mode, throwing this error:
![image](https://user-images.githubusercontent.com/58902941/82527040-45a9c480-9aea-11ea-9d52-feaaf465ece0.png)
I'm currently running Optifine 1.15.2 prerelease 18, with OptiForge,
and my GPU is an AMD RX 5700 XT.

**Comment by LoganDark** [comment]
Your shader is throwing an error when Immersive Portals tries to do its fancy framebuffer thang.

Does this happen with any shader or just one?

Relevant code:
https://github.com/qouteall/ImmersivePortalsModForForge/blob/a1f681d7c727b11a76b4084634c661e697a92c25/src/main/java/com/qouteall/immersive_portals/optifine_compatibility/OFHelper.java#L17-L39

**Comment by Jarfeh** [comment]
It happens with every shader I've tried
quickE: that was a fast response time!

**Comment by LoganDark** [comment]
What's your video card/GPU?

> quickE: that was a fast response time!

I get instant notifications via Discord, it's even faster than GitHub's emails :P

**Comment by Jarfeh** [comment]
Dang, anyways my card is the AMD RX 5700 XT

**Comment by qouteall** [comment]
It's your video card or video card driver's issue. Because your video card cannot do depth format conversion, it will render portal through wall if not in compatibility mode.
Portal in portal will not be visible in compat mode

**Comment by Jarfeh** [comment]
Dang, thank you for the fast response though, I figured I was going to have problems along the way with this card!
QuickE: Actually now that I think about it, I hadn't had this problem in earlier versions of the mod.

**Comment by LoganDark** [comment]
> QuickE: Actually now that I think about it, I hadn't had this problem in earlier versions of the mod.

Because earlier versions of the mod didn't detect it. But this one does.

If it's an issue with every shader, then it is *actually* your video card.

**Comment by Jarfeh** [comment]
Dang, thanks again for the fast response time!
quickE: I say dang too much :P

**Comment by LoganDark** [comment]
Dang

quickE: Dang
