### ISSUE TITLE
Crash on launch with Optifine (Forge 1.14.4)

### ISSUE THREAD

**Issue by Nindota** [qouteall/ImmersivePortalsModForForge#113]
For whatever reason, the 1.14.4 version crashes on launch when I'm using Optifine, which is made somewhat annoying as there is no crash log.

**Comment by qouteall** [comment]
Then show the log. it's in .minecraft/logs/latest.log or debug.log

**Comment by Nindota** [comment]
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4682091/latest.log)
I would've replied sooner, but I don't actually know what happened last night. The last 11 hours are just gone from my memory.

**Comment by qouteall** [comment]
It's the reentrance issue which is caused by forge. You can try to uninstall optiforge

**Comment by Nindota** [comment]
I just get another crash without Optiforge installed
[crash-2020-05-26_09.52.14-client.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4682297/crash-2020-05-26_09.52.14-client.txt)

**Comment by qouteall** [comment]
Maybe one mod that you installed is not compatible with optifine.
1.14 version of this mod is no longer supported

**Comment by Nindota** [comment]
I've already tested all the mods. The only thing that doesn't work with it is Optifine itself.

**Comment by Nindota** [comment]
I understand that the 1.14 version of the mod is no longer supported, but the fact that Optifine is causing it not to work just seems rather odd.
I know it's not one of the other mods I've got installed that's not compatible with Optifine as I've been using all of these mods with Optifine for about a week now, and only tried adding the Immersive Portals mod yesterday. I ended up finding that having Optifine installed in addition to your mod was the only time it would crash.

**Comment by qouteall** [comment]
IP's compatible with OptiFine 1.14.4 HD U F5. It may be a 3-mod compatibility issue.

**Comment by qouteall** [comment]
And the crash report says that you didn't install IP

**Comment by Nindota** [comment]
Must've removed it and Optiforge from the mods folder by accident rather than just Optiforge.
Just tried to run Minecraft without Optiforge but still with IP in the mod folder, and got an updated crash report with it included if that changes anything.
[crash-2020-05-26_10.18.30-client.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4682461/crash-2020-05-26_10.18.30-client.txt)

**Comment by qouteall** [comment]
The latest Forge 1.14 breaks with OptiFine. It's not this mod's issue
Using older forge (28.1.114) can fix it.
