### ISSUE TITLE
Incompatibility with preview_OptiFine_1.15.2_HD_U_G1_pre23

### ISSUE THREAD

**Issue by Blugori** [qouteall/ImmersivePortalsModForForge#118]
Hi, I was trying to launch minecraft with immersive portals 0.20 and optifine pre release 23, but when the game start I get a screen saying "error loading mods, 1 error has occured during loading, immersive portals encountered an error during the sided_setup event phase"

I'm using Forge 31.2.0, immersive portal 0.20 and mixin 1.0.3
Even without any other mods it wont work.
Everything was fine with older pre releases of optifine
![immersiveportalbug](https://user-images.githubusercontent.com/66573974/83981721-b6d9dc00-a920-11ea-9f66-0ab3aa6e13c9.PNG)

thanks for your concern ! (edit : I started an issue on optifine github too)

EDIT : I tried again to launch the game to get the latest.log and got more details : 
![crashimmersiveportal](https://user-images.githubusercontent.com/66573974/84016328-69d82300-a97d-11ea-8a10-1496cdf11585.png)

[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4745157/latest.log)

**Comment by qouteall** [comment]
fixed in 0.21
