### ISSUE TITLE
Crashes on Forge 28.1.114

### ISSUE THREAD

**Issue by claytoncasey01** [qouteall/ImmersivePortalsModForForge#12]
When loading into the world I get glitched out graphics with everything being black and after about 10 seconds it crashes to desktop. Strangely no crash logs are generated, attaching recent log and debug log instead.

[debug.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4052208/debug.log)
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4052209/latest.log)
[hs_err_pid6536.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4052251/hs_err_pid6536.log)
![image](https://user-images.githubusercontent.com/4170131/72234807-bcfba480-359c-11ea-80f8-271e16b68b13.png)

**Comment by qouteall** [comment]
Show the crash report

**Comment by claytoncasey01** [comment]
> Show the crash report

Add logs and image example.

**Comment by qouteall** [comment]
Are you using old version of this mod? The latest is 0.9. Does it crash without optifine?

**Comment by qouteall** [comment]
And the optifine version should be f5

**Comment by claytoncasey01** [comment]
> e version should be f5

Just downloaded it right before I posted so it's 0.9 and Optifine is F5 as well.

**Comment by qouteall** [comment]
the dedicated server crashes? show the server crssh report.
Does it crash without optifine?

**Comment by qouteall** [comment]
You said you removed all other mods but optifine is a mod.

**Comment by qouteall** [comment]
Try to upgrade your video card driver? Or update windows 10 to the newest version?
And it seems that you installed warp mod and world edit

**Comment by qouteall** [comment]
It seems that OpenGL crashed. weird

**Comment by qouteall** [comment]
Can you play minecraft with shader and without this mod normally?

**Comment by claytoncasey01** [comment]
> Can you play minecraft with shader and without this mod normally?
1. Client only crashes, will test without Optifine later today and update you.
2. Driver is up to date and windows 10 is the newest version. Graphics card is 1080ti, I am running at 4k res.
3. I can play fine with the shaders without this mod, no issues until I added this mod in.

**Comment by claytoncasey01** [comment]
> You said you removed all other mods but optifine is a mod.

So without Optifine it seems to work perfectly fine, so it must be Optifine itself causing it. I have tried it with Optifine .jar still in the folder but the shaders disabled and it still crashes. Only works when Optifine is completely removed.

**Comment by qouteall** [comment]
You can run it in dev environment with OptiFine. See readme.
But the methods that are transformed by OptiFine will have mismatch line numbers so you can't put breakpoints in it.

**Comment by qouteall** [comment]
Another person encountered the same issue.

**Comment by qouteall** [comment]
It crashes after recreating frame buffer with stencil component. So maybe it's correlated with it. I will make a debug version of this mod without recreating fb.

**Comment by qouteall** [comment]
Install the newest version of this mod and go to .minecraft/config/immersive_portals-client.toml
then edit it. set compatibility_render_mode to true. And then go into the game with optifine and without shaders.
If this file does not exist then open the game and close.

**Comment by claytoncasey01** [comment]
> Install the newest version of this mod and go to .minecraft/config/immersive_portals-client.toml
> then edit it. set compatibility_render_mode to true. And then go into the game with optifine and without shaders.
> If this file does not exist then open the game and close.

Same issue. Attaching error log from most recent crash.
[hs_err_pid1108.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4062722/hs_err_pid1108.log)

**Comment by qouteall** [comment]
Show the game's log

**Comment by qouteall** [comment]
This time it's different. It crashes when rendering a portal. Can you play normally without any portal nearby with optifine with this mod in compatibility mode?

**Comment by qouteall** [comment]
Did you turn off render regions?
