### ISSUE TITLE
Crash On Game Startup

### ISSUE THREAD

**Issue by Kilomegaminx** [qouteall/ImmersivePortalsModForForge#128]
When I start up the game, my game crashes. Do you know what is going on?
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4801636/latest.log)

**Comment by Kilomegaminx** [comment]
I just recently discovered that there is an issue with optifine that was making it fail. I really love the features that optifine provides. Would you please try to fix that. Thank You!

**Comment by qouteall** [comment]
Try to use optifine pre24

**Comment by Kilomegaminx** [comment]
That did not work either.
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4807105/latest.log)

**Comment by Kilomegaminx** [comment]
I got it to work with pre28
