### ISSUE TITLE
Entities inconsistently travel through portals

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#13]
Entities like items, arrows, and even mobs do not travel through portals consistently. For non-mobs, they randomly travel or don't travel through the portal. For mobs, my testing has shown that they consistently travel through vertical portals, but never through horizontal portals.

Edit: Further testing indicates that mobs with some horizontal momentum tend to travel through portals while those that fall straight down do not.

[Video demonstration](https://youtu.be/PUCFLerv1F8)

**Comment by qouteall** [comment]
probably fixed

**Comment by qouteall** [comment]
check the newest version

**Comment by davidthehat** [comment]
Can confirm, appears fixed
