### ISSUE TITLE
Portals Not Connecting 1.16.1

### ISSUE THREAD

**Issue by raydgc123** [qouteall/ImmersivePortalsModForForge#149]
Without Immersive Portals, my portals connect properly. Both have the same dimensions and face the same direction. But with Immersive Portals on, when i light up the portal, they create new portals.

**Comment by qouteall** [comment]
You need to break the portal block on the other side. It links to an empty obsidian frame

**Comment by raydgc123** [comment]
Lol thank you for the quick response. It's fixed now sorry for the bother. Great mod btw.
