### ISSUE TITLE
Mirrors improperly reflect certain entities

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#15]
The mirror image of a painting shows the wooden backside texture.

The mirror image of a minecart is inverted.

The mirror image of a boat is inverted and contains z-fighting.
![2020-01-14_09 05 37](https://user-images.githubusercontent.com/24359213/72351222-f112ba80-36ad-11ea-809a-7193c726670b.png)
![2020-01-14_09 11 27](https://user-images.githubusercontent.com/24359213/72351223-f112ba80-36ad-11ea-8255-d3d1aab23755.png)

**Comment by qouteall** [comment]
probably fixed

**Comment by qouteall** [comment]
check 0.11 version
