### ISSUE TITLE
Crashes on 1.16.2 possible NoClassDefFoundError

### ISSUE THREAD

**Issue by alorg** [qouteall/ImmersivePortalsModForForge#153]
[crash-2020-08-27_13.40.55-client.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/5136401/crash-2020-08-27_13.40.55-client.txt)

Here is the full crash log

**Comment by qouteall** [comment]
I need to see the log

**Comment by qouteall** [comment]
Try to launch the game again? If it does not happen again then it could be a concurrency issue

**Comment by alorg** [comment]
Its cool I was missing a library  for another mod and that was causing the crash, working great thansk
