### ISSUE TITLE
Mirrors can be pushed

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#16]
Shulkers, shulker boxes, and pistons can move mirrors, leading to weird results. Attached are my experiments with shulkers.

[Video](https://youtu.be/aQ7iUpHXUPA)

![2020-01-14_09 32 11](https://user-images.githubusercontent.com/24359213/72354355-9b411100-36b3-11ea-8fd7-737be1759994.png)

**Comment by qouteall** [comment]
probably fixed

**Comment by qouteall** [comment]
check 0.11 version
