### ISSUE TITLE
crash with optifine and immersive portals

### ISSUE THREAD

**Issue by catweaselirl** [qouteall/ImmersivePortalsModForForge#161]
I am using immersive-portals-0.4-mc1.16.3-forge and preview_OptiFine_1.16.3_HD_U_G4_pre1 (the stable build of optifine has the same issue) and the game crashes upon loading a world. World loads just fine with either on their own. It may also be important to note that the same issue occurs when using the fabric version of the mod in conjunction with a second fabric mod that enables optifine.

Log: https://pastebin.com/JthpK6pD

**Comment by tontyGH** [comment]
i've had the same issue, and disabling render regions didn't help

**Comment by BruhMoment-cmd** [comment]
Same I tried reinstalling my launcher and it didn't work

**Comment by qouteall** [comment]
Use 1.16.5 with the latest IP and optifine
