### ISSUE TITLE
Crash when giant zombies or zombie horses catch on fire

### ISSUE THREAD

**Issue by Blugori** [qouteall/ImmersivePortalsModForForge#163]
Minecraft ver : 1.16.3
Forge ver : 34.1.0
Immersive portal ver : immersive-portals-0.4-mc1.16.3-forge

When I summon a giant zombie or zombie horse when it's day, the game crash. When I summon them at night and then manually or naturally put the day, the game crash ;(

Thanks for your work !

Logs : 
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/5326959/latest.log)
[crash-2020-10-04_18.59.08-server.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/5326961/crash-2020-10-04_18.59.08-server.txt)
[debug.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/5326962/debug.log)

**Comment by qouteall** [comment]
Will be fixed in the next version. You can disable "enableAlternateDimensions" for now.

**Comment by Blugori** [comment]
Thanks a lot !
