### ISSUE TITLE
Alternate Overworld weather is not synced with Overworld weather.

### ISSUE THREAD

**Issue by Giggitybyte** [qouteall/ImmersivePortalsModForForge#17]
See the video [here](https://youtu.be/-KMKN1Ln42s).

Forge Version 1.14.4-28.1.111
Immersive Portals Version 0.10

**Comment by qouteall** [comment]
probably fixed

**Comment by Giggitybyte** [comment]
Sweet. Thank you.
Please let me know when you release 0.11 on CurseForge with this fix.

**Comment by qouteall** [comment]
check 0.11 version

**Comment by Giggitybyte** [comment]
This appears to be fixed. Thank you.
