### ISSUE TITLE
1.16.1 Version not working with ViveCraft 1.16.1

### ISSUE THREAD

**Issue by mike1000195** [qouteall/ImmersivePortalsModForForge#171]
crashes upon startup, some incompatibility definitely happening

**Comment by baconlover209** [comment]
also having this problem but on other versions as well

**Comment by froyo4u** [comment]
This is known to not work with vivecraft even by vivecraft themselves issue resolved, pls close

**Comment by mike1000195** [comment]
some documentation from mod developers stating incompatible mods to cut down on issue listings would be helpful, but i gues we cant have everything.

thanks for the info.

**Comment by froyo4u** [comment]
> 
> 
> some documentation from mod developers stating incompatible mods to cut down on issue listings would be helpful, but i gues we cant have everything.
> 
> thanks for the info.

they do actually: http://www.vivecraft.org/forge-mod-compatibility/
