### ISSUE TITLE
Mixin Bootstrap Crash w/ Better Foliage

### ISSUE THREAD

**Issue by WenXin20** [qouteall/ImmersivePortalsModForForge#18]
`Minecraft v1.14.4`
`Forge v28.1.115`
`Immersive Portals v0.10`
`Mixin Bootstrap v1.0.0`
[`Kottle v1.4.0`](https://www.curseforge.com/minecraft/mc-mods/kottle)
[`Better Foliage v2.5.0`](https://www.curseforge.com/minecraft/mc-mods/better-foliage)

Since both Immersive Portals & Better Foliage require Mixin Bootstrap to function, I'm getting a crash as soon as I try to start the game. Is this something that can be fixed?
Also reported at octarine-noise/BetterFoliage#270
[Crash Log](https://gist.github.com/WenXin20/ecf10e64c1d0420ec4dc1bdf7bb0b869)

**Comment by qouteall** [comment]
It seems correlated with optifine. Try to only install better foliage and optifine and test it.

**Comment by WenXin20** [comment]
It worked fine with Better Foliage & Optifine when installed with Mixin and Kottle. 
When Immersive Portals is added without Optifine to Better Foliage, it works fine, but when Optifine is added crashes.

So it seems like all 5 mods have to be installed for the crash to happen.

**Comment by qouteall** [comment]
wow, 5-mod interaction.

**Comment by WenXin20** [comment]
Yeah, crazy!

**Comment by qouteall** [comment]
Did you disable render regions option?

**Comment by octarine-noise** [comment]
MixinBootstrap only adds Mixin, and Kottle only adds Kotlin, but they don't have mixins themselves. So, hopefully only 3-mod interaction :)

**Comment by qouteall** [comment]
ok I found it. When I mixin ActiveRenderInfo it loads PortalPlaceholderBlock then it loads Block then trigger better foliage's mixin

**Comment by qouteall** [comment]
check 0.11 version

**Comment by WenXin20** [comment]
No crash anymore, but round logs aren't working from Better Foliage. But that might be on their end. 

A major issue was introduced though. It seems any mod that adds a dimension will not load correctly. Tested it with [`Good Night Sleep v1.0.1`](https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep). 
[Log](https://gist.github.com/WenXin20/78b2918126ce45e80749ef075edbd29f)

**Comment by WenXin20** [comment]
Just found out that round logs work if Immersive Portals is removed.

**Comment by qouteall** [comment]
I fixed the issue that good night's sleep does not load. But it has another serious issue with good night's sleep

**Comment by qouteall** [comment]
And /portal tpme command seems broken

**Comment by qouteall** [comment]
Well I will release a new version so that I at least loads.

**Comment by WenXin20** [comment]
When TofuCraft was installed, it was also having trouble loading it's dimension. I'll have to do the testing tomorrow with the new version

**Comment by octarine-noise** [comment]
> 
> 
> ok I found it. When I mixin ActiveRenderInfo it loads PortalPlaceholderBlock then it loads Block then trigger better foliage's mixin

Sorry, but it's my first time using Mixin, so I'm kind of lost here. Can you explain why this is a problem, or what exactly we are doing that is disallowed, causing our mixins to "resonate" this way?

**Comment by qouteall** [comment]
@octarine-noise Actually I don't really understand these things. When a class loads then it will do Mixin transformation. On MixinActiveRenderInfo's injection I use PortalPlaceHolderBlock class which extends Block class. And then it will load Block class and then it will do transformation for Block class. But Mixin does not allow transforming a class when transforming another class so it crashes. But in normal cases PortalPlaceHolderBlock will not be loaded when applying Mixin. It involves some complex mechanic of Mixin and modlauncher and OptiFine.
So you didn't misuse Mixin. It's actually caused by my Mixin usage. -_-

**Comment by qouteall** [comment]
If similar crash happen again then you can debug it in IDE and see which class loads which

**Comment by qouteall** [comment]
I will check the round log issue later
