### ISSUE TITLE
Dimension stack GUI doesn't list mod's dimensions in forge 35.0.18 (MC 1.16.4)

### ISSUE THREAD

**Issue by solarblindfull** [qouteall/ImmersivePortalsModForForge#180]
Hello ! Thank a lot for this very good mod !

I'm on Forge 35.0.18 (minecraft 1.16.4) and I've an issue with the dimension stack GUI of the lastest version of your mod (immersive-portals-0.7-mc1.16.3-forge). I've the same issue in the lastest Fabric version too.

It doesn't list my mod's dimensions as you can see in the screenshot below. 

![Mods_file_screenshot](https://user-images.githubusercontent.com/66645032/99293564-22ff2b00-2843-11eb-9a58-82e11a95981e.PNG)
![Dimension_Stack_AddADimension_GUI](https://user-images.githubusercontent.com/66645032/99293584-298da280-2843-11eb-94fe-a112a6d758c5.PNG)

For example, I've installed Undergarden and Bumblezone dimensions mods. It works very well but the mods aren't in the GUI.

Can you see what's wrong please ?
Thank you very much
Have a good day

**Comment by qouteall** [comment]
It's probably fixed (will be in the next version)

**Comment by solarblindfull** [comment]
Thank you very much for your quick answer ! 
That's great. For when have you planned to release the next version please ?  : D

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsModForForge/releases/tag/v0.8-1.16-forge

**Comment by solarblindfull** [comment]
Hello !

Thank for your reply.
I tested your new version and all works very well. Thank you very much !

Can you tell me more about the two new options, especially about the "loop" one please ?

Have a good day

**Comment by qouteall** [comment]
see the discord server https://discord.gg/BZxgURK    #development

**Comment by solarblindfull** [comment]
Wow ! Soooo many possibilities with the loop ! : D''''''''''''''
And the "respect space ratio" one is truly funny ! Can't wait to test it !

Thank so much for this wonderful mod 
Have a very good day
