### ISSUE TITLE
Please add 1.12.2 Support

### ISSUE THREAD

**Issue by rvveber** [qouteall/ImmersivePortalsModForForge#184]
I know its an entirely different codebase.
But BetterPortals is not an alternative!
It's not nearly as flexible as your mod.

I could probably never do this
https://www.youtube.com/watch?v=st3Jiq0BdP4

with betterportals alone :c

Could you please backport this mod? 
I would be incredibly grateful!

**Comment by ImSpaceLover** [comment]
If it's not a good alternative for you - just use 1.16 version

**Comment by rvveber** [comment]
i can't because i depend on other mods that only exist for 1.12
we can't update everything all the time..  because not everyone updates everything all the time
