### ISSUE TITLE
Bugg

### ISSUE THREAD

**Issue by DanishDisaster** [qouteall/ImmersivePortalsModForForge#190]
When i use optifine it crashes when i go in game

**Comment by froyo4u** [comment]
> When i use optifine it crashes when i go in game

Disable Render Regions. It is in Video Settings --> Performance

**Comment by PenumbraStar** [comment]
Same issue but render regions is disabled, for me it crashes upon trying to start minecraft. Below is the log file as a crash report did not generate.
The error I narrowed it down to is
`[18Jan2021 18:33:46.254] [Render thread/FATAL] [mixin/]: Mixin apply failed imm_ptl_mixins_optifine.json:MixinShaders_Swap -> net.optifine.shaders.Shaders: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field activeDrawBuffers was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field activeDrawBuffers was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl.refmap.json`
Looks like a mixin issue, but I can not tell if its optifines fault or something with this mod, in addition this now was working fine until about 2 days ago after which this issue started to occur.
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/5832771/latest.log)

**Comment by Moleculor** [comment]
@PenumbraStar 
> Looks like a mixin issue, but I can not tell if its optifines fault or something with this mod, in addition this now was working fine until about 2 days ago after which this issue started to occur.
> [latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/5832771/latest.log)

Well, you're using Forge 35 and Optifine **pre_G7** when I believe **G6** started requiring Forge 36. So your Forge and Optifine are likely incompatible with one another, and I have no idea if Immersive Portals is compatible with Forge 36, Optifine G6 *or* G7. 

So... stop that.

**Comment by PenumbraStar** [comment]
I had the same issue with version G6, and an older forge version, I appreciate you trying to help though.

On Jan 18, 2021, at 8:09 PM, Moleculor <notifications@github.com> wrote:

﻿

@PenumbraStar<https://github.com/PenumbraStar>

Looks like a mixin issue, but I can not tell if its optifines fault or something with this mod, in addition this now was working fine until about 2 days ago after which this issue started to occur.
latest.log<https://github.com/qouteall/ImmersivePortalsModForForge/files/5832771/latest.log>

Well, you're using Forge 35 and Optifine pre_G7 when I believe G6 started requiring Forge 36. So your Forge and Optifine are likely incompatible with one another, and I have no idea if Immersive Portals is compatible with Forge 36, Optifine G6 or G7.

So... stop that.

**Comment by Moleculor** [comment]
> I had the same issue with version G6, and an older forge version, I appreciate you trying to help though. 

That's because G6 only works for a very small narrow window of versions. Forge 36 and/or *possibly* 35.1.36, 35.1.37.  

To break it down: 
G5 requires Forge 35, up to *but not including or past* 35.1.36. 
G6 requires Forge 35.1.36 or 35.1.37 at a minimum, and may actually require Forge 36. 
G7 requires Forge 36.

All of which is printed in Optifine's changelogs and download pages. Sorta. It's not really entirely clear why the changelog for G6 says 'works with 35.1.36' but says 36.0.0 on the download page. 

Either way, you're still doing incompatible things with incompatible things.

**Comment by code2828** [comment]
> > When i use optifine it crashes when i go in game
> 
> Disable Render Regions. It is in Video Settings --> Performance

I'm encountering the same problem. Using G8 + Forge 36. How do I disable Render Regions if I can't even get in to the game?

**Comment by code2828** [comment]
nvm I just took a look at other similar issues and found out that only G7 is supported.
