### ISSUE TITLE
Multiplayer Server crashes when Immersive Portals is installed (Server Tick 60+)

### ISSUE THREAD

**Issue by DarkHermit** [qouteall/ImmersivePortalsModForForge#193]
Hello! 

so I've been trying to install this mod on my minecraft server, but every single time, and ONLY with this mod, my server gives me the error saying that the max server tick has gone over 60.00s and has to close... and I tried the technic of changing the max server tick to -1, and yes, the server does stay open, but everything is frozen, no mobs are moving, etc

am I doing something wrong or is this mod just not suitable for servers?

thx

**Comment by DarkHermit** [comment]
I- I'm already on 1.16.4 as I said lol

**Comment by Lartza** [comment]
In the crash report you are using 1.16.1 and don't even have Immersive Portals

**Comment by Moleculor** [comment]
And that crash report is from September of last year.

**Comment by bailboy101** [comment]
I am having this issue as well. Log attatched. No issues for several days and then suddenly when I am not close to a portal it crashes. I see mixin errors from Immersive Portals as the last errors
[crash-reports_crash-2021-01-09_14.12.21-server.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/5791680/crash-reports_crash-2021-01-09_14.12.21-server.txt)

**Comment by Moleculor** [comment]
@bailboy101 
> I am having this issue as well. Log attatched. No issues for several days and then suddenly when I am not close to a portal it crashes. I see mixin errors from Immersive Portals as the last errors
> [crash-reports_crash-2021-01-09_14.12.21-server.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/5791680/crash-reports_crash-2021-01-09_14.12.21-server.txt)

Your crash is not the same. It starts from a very different area: tripwire hooks. I remember seeing this exact problem a week or two ago. I bet if you look at your debug.log you're going to see that Dungeon Crawl is taking forever to generate a dungeon. You need to find out if Dungeon Crawl has fixed this problem.

EDIT: They have worked around it by removing tripwire hooks from their generation for now. Go update Dungeon Crawl.
