### ISSUE TITLE
[Suggestion] Portality Intergration?

### ISSUE THREAD

**Issue by Notawallplan** [qouteall/ImmersivePortalsModForForge#2]
Title, really. Would be neat if we could see the destination of portals in the Portally mod.

**Comment by qouteall** [comment]
What is Portally mod

**Comment by Notawallplan** [comment]
https://www.curseforge.com/minecraft/mc-mods/portality

**Comment by qouteall** [comment]
you can customize portals using commands. tones of mods provide tones of custom classical portals and I won't integrate with all of them. I will only integrate with popular dimension mods such as twilight forest.
