### ISSUE TITLE
End portal stays when filled with air after being broken in creative mode

### ISSUE THREAD

**Issue by GrantGryczan** [qouteall/ImmersivePortalsModForForge#204]
I broke the end portal frame in creative mode, and the immersive portal stayed. I tried `/fill`ing it with air afterward and that also did not help.

![2021-01-29_03 12 33](https://user-images.githubusercontent.com/14056899/106249235-19e5ef00-61e0-11eb-9c66-c4ae95e1cf28.png)
(The rendering issue is just because I created another portal afterward in the same spot to test something.)

This has seemingly permanently ruined this area of my creative world. If end portals could automatically be removed when their frame is destroyed, if not when the portal blocks are removed, that would be best.

I would consider this a severe issue since it can ruin an area of a creative world (or survival if there is a mod to remove end portals).

**Comment by Moleculor** [comment]
Ah... have you tried looking at it and invoking the arcane magicks with `/portal eradicate_portal_clutter` or, at worst, `/portal delete_portal`? <https://github.com/qouteall/ImmersivePortalsMod/wiki/Commands-Reference>

(Never actually experienced this issue myself, but you're never going to be able to kill an `@e[type=immersiveportals:immersive_portal]` or whatever its type is by smothering it with air. You might as well be smothering a pig with air, or a zombie with air.

(These aren't blocks. You can't replace things that aren't blocks with blocks.)

**Comment by GrantGryczan** [comment]
@Moleculor I didn't think the immersive portal itself was made of blocks, but I thought removing the portal blocks would remove the immersive portal, the same way removing the blocks of a nether portal removes the immersive portal. But apparently there is no such detection built in for end portals. Breaking the end frame doesn't actually break the end portal blocks, and this mod removes the hitbox for those blocks, so I had to use `/fill` to remove them.

The first command worked though, thanks! But this is still an issue in general, since you really should not have to use commands to fix this.

**Comment by qouteall** [comment]
Using the command is the intended way to remove the end portal. See the wiki for more details. And creative mode non-OP player can use that portal command. End portal is not intended to be breakable by normal means. So it's not an issue
