### ISSUE TITLE
Seeing Character From Impossible Angles

### ISSUE THREAD

**Issue by JTepper23** [qouteall/ImmersivePortalsModForForge#229]
The only mods installed are the Fabric Mod loader, Fabric API, and the immersive portals mod and core on 1.16.5. I have two bi-way portals that are near each other. When I go partly through one of the portals, I can see myself in the other portal even though I don't believe this should be possible. The two portals lead to a room that is very similar to the starting room.
![1](https://user-images.githubusercontent.com/68556291/111082316-fb149100-84dd-11eb-8ae3-023e92708c60.png)
^ The two portals lead from the top and the front of this smaller room to the top and the front of a larger room. 

![2](https://user-images.githubusercontent.com/68556291/111082317-fbad2780-84dd-11eb-98a3-49db1b7bf65a.png)
^ The smaller room from the inside where the portals are located.

![3](https://user-images.githubusercontent.com/68556291/111082318-fcde5480-84dd-11eb-8959-b23a78cd91ed.png)
![4](https://user-images.githubusercontent.com/68556291/111082320-fd76eb00-84dd-11eb-8df5-935288d52abb.png)
^ When I pass slightly through one of the portals travelling from the bigger room to the smaller room, I can see myself in the other poral. None of the portals or bi-faced but they are bi-way. The portals are located where my "image" appears.

**Comment by qouteall** [comment]
Does it happen with "crossPortalEntityRendering" disabled?

**Comment by JTepper23** [comment]
Yeah, disabling "crossPortalEntityRendering" does fix the issue.
