### ISSUE TITLE
Crash on launch 1.15.2

### ISSUE THREAD

**Issue by Sunekaer** [qouteall/ImmersivePortalsModForForge#23]
Hi

The game crashed on launch.
Log: https://hastebin.com/lagibotapa.php

1.15.2-forge-31.0.1

	Mod List: 
		forge-1.15.2-31.0.1-client.jar Minecraft {minecraft@1.15.2 NONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 NONE}
		tombstone-4.2.0-1.15.1.jar Corail Tombstone {tombstone@4.2.0 NONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 NONE}
		UndergroundMaterials-1.15.x-1.3.2.jar Underground Materials {undermat@1.3.2 NONE}
		BonsaiTrees-2.1.0.1.jar Bonsai Trees 2 {bonsaitrees2@2.1.0.1 NONE}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 NONE}
		speedyhoppers-1.15.2-1.jar Speedy Hoppers {speedyhoppers@1.15.2-1 NONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 NONE}
		immersive-portals-0.1(for+mc+1.15+with+forge).jar Immersive Portals {immersive_portals@0.1 NONE}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 NONE}
		TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 NONE}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 NONE}
		forge-1.15.2-31.0.1-universal.jar Forge {forge@31.0.1 NONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 NONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 NONE}
		GameMenuModOption-1.15.2-1.2.jar GameMenuModOption {gamemenumodoption@1.2 NONE}
		SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 NONE}
		quartz-chests-1.1.0.4.jar Quartz Chests {quartzchests@1.1.0.4 NONE}
		FruitTrees-1.15.2-1.1.5.jar Fruit Trees {fruittrees@1.1.5 NONE}

**Comment by Xero-Gravity** [comment]
Same, it's not working now. This is the only mod that crashed the game, cannot load into any worlds > Instant CTD

**Comment by qouteall** [comment]
Maybe it's fixed in 0.2 version

**Comment by Xero-Gravity** [comment]
> 
> 
> Maybe it's fixed in 0.2 version

Not sure about OP's problems, but I'm an idiot XD. Didn't have MixinBootstrap installed before. It's working now.

**Comment by Xero-Gravity** [comment]
> 
> 
> Hi
> 
> The game crashed on launch.
> Log: https://hastebin.com/lagibotapa.php
> 
> 1.15.2-forge-31.0.1
> 
> ```
> Mod List: 
> 	forge-1.15.2-31.0.1-client.jar Minecraft {minecraft@1.15.2 NONE}
> 	inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 NONE}
> 	tombstone-4.2.0-1.15.1.jar Corail Tombstone {tombstone@4.2.0 NONE}
> 	playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 NONE}
> 	UndergroundMaterials-1.15.x-1.3.2.jar Underground Materials {undermat@1.3.2 NONE}
> 	BonsaiTrees-2.1.0.1.jar Bonsai Trees 2 {bonsaitrees2@2.1.0.1 NONE}
> 	mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 NONE}
> 	speedyhoppers-1.15.2-1.jar Speedy Hoppers {speedyhoppers@1.15.2-1 NONE}
> 	jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 NONE}
> 	immersive-portals-0.1(for+mc+1.15+with+forge).jar Immersive Portals {immersive_portals@0.1 NONE}
> 	EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 NONE}
> 	TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 NONE}
> 	campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 NONE}
> 	forge-1.15.2-31.0.1-universal.jar Forge {forge@31.0.1 NONE}
> 	bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 NONE}
> 	FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 NONE}
> 	GameMenuModOption-1.15.2-1.2.jar GameMenuModOption {gamemenumodoption@1.2 NONE}
> 	SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 NONE}
> 	quartz-chests-1.1.0.4.jar Quartz Chests {quartzchests@1.1.0.4 NONE}
> 	FruitTrees-1.15.2-1.1.5.jar Fruit Trees {fruittrees@1.1.5 NONE}
> ```

Update your forge, dude. We're on 31.0.14 as the latest experimental build, but maybe that will work?

**Comment by Sunekaer** [comment]
"dude" .14 was out when this issue was created... and yes its fix in the new version of the mod thanks
