### ISSUE TITLE
Crash when using 31.0.13

### ISSUE THREAD

**Issue by vico93** [qouteall/ImmersivePortalsModForForge#24]
Crash log: https://paste.dimdev.org/yewuwayoko.rb

I just updated from 31.0.1 to 31.0.13 and this just happens at launch.

Since it says something related to MixinBootstrap-1.0.1.jar i suspected it was related to that dependency ImmersivePortals have (for forge).

Anyway thanks for this mod!

**Comment by qouteall** [comment]
fixed in 0.3 version
