### ISSUE TITLE
size change?

### ISSUE THREAD

**Issue by gooblorshks** [qouteall/ImmersivePortalsModForForge#246]
When I make a portal that is 2 times bigger than the first one, instead of becoming smaller or bigger, I stay the same size.

Can you please make it so that you can change size when you go through a bigger portal?

**Comment by gooblorshks** [comment]
Also is it possible to make it work with the Pehkui mod? There is one version of the Pehkui mod that is for forge.
![pehkui thingyyyyy](https://user-images.githubusercontent.com/83406574/116599811-8dd68700-a8f6-11eb-875f-aa03badfbc32.png)

**Comment by humematt190** [comment]
this isn't compatible with pehkui forge yet

**Comment by froyo4u** [comment]
YEAH
