### ISSUE TITLE
The game crashes with the mod installed.

### ISSUE THREAD

**Issue by Begnom** [qouteall/ImmersivePortalsModForForge#249]
It just crashes without any crash report.
GTX 1660 Super
Ryzen 5 2600
16Gb Ram

Mods:
Optifine
Security Craft
Sound Filters
World Edit
GamemodeOverhaul

**Comment by froyo4u** [comment]
what version of OptiFine

**Comment by Begnom** [comment]
1.16.5 HD G6 if that's what you mean

**Comment by froyo4u** [comment]
only G7 is compatible

**Comment by Begnom** [comment]
Works now, thanks

**Comment by froyo4u** [comment]
np
