### ISSUE TITLE
portal helper not working with far away portals

### ISSUE THREAD

**Issue by hjhyhg** [qouteall/ImmersivePortalsModForForge#252]
when i link up two villages with a portal it won't work they are 5 thousand blocks apart

**Comment by hjhyhg** [comment]
and also i used the exact portal for both of those sides

**Comment by froyo4u** [comment]
Turn up your nether portal searching range in the config. I know it says nether portal but it applies to all portals

**Comment by qouteall** [comment]
Turning the searching range big could make portal generation very laggy. You can use commands to set portal destination, check the wiki

**Comment by hjhyhg** [comment]
ok
