### ISSUE TITLE
just add the sticks simple as that or give me a command to make them 

### ISSUE THREAD

**Issue by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [qouteall/ImmersivePortalsModForForge#264]
just add the sticks simple as that or give me a command to make them

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
command sicks i need

**Comment by RemagOfficial** [comment]
no

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
yes

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
i need them had to resort to this [https://minecraft.tools/en/command-33147-immersive-portals-command-booklet](url)

**Comment by RemagOfficial** [comment]
just use fabric

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
one q why cant you just port it over it must be simple to port?

**Comment by RemagOfficial** [comment]
its really not

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
hmm then why not just give a command or resource pack to fix this issue? That should fix the its really not part.

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
im not asking to make the pehkui mod compatible just a simple request to make this mod a little better

**Comment by RemagOfficial** [comment]
tha fabric version is better

**Comment by RemagOfficial** [comment]
use it

**Comment by froyo4u** [comment]
if you think it's so simple to just port them over, do it yourself. Good luck

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
how

**Comment by RemagOfficial** [comment]
learn java and add the command sticks

**Comment by froyo4u** [comment]
oh idk, you think it's so simple to do, figure it out if you really care. now stop spamming this issue please

**Comment by RemagOfficial** [comment]
easy, right?

**Comment by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [comment]
ok i will stop spamming this i just dont understand why make it such a big deal and fabric is bad only because of mod support   no good mod support   just like 1.12.2 to 1.16.4 . like most gun mod are gone to the past v's

**Comment by froyo4u** [comment]
that doesn't even make sense my dude. Stop arguing about it. You're the one making it a big deal

**Comment by RemagOfficial** [comment]
fabric does support 1.16.4 tho

**Comment by piousminion** [comment]
> 
> 
> just use fabric

Sure, as soon as all the other major mods use it and/or forge and fabric are made compatible.  Until then, telling people to "just use fabric" and dump all their other favorite mods is both closed-minded and insulting.  Surely you're better than that.
