### ISSUE TITLE
[suggestion] dimension

### ISSUE THREAD

**Issue by DjTylerD** [qouteall/ImmersivePortalsModForForge#27]
hello I find your mod excellent, I test it since update 1.15.2. forge
  this morning I just saw and tested the dimensions 2 3 4, I love the 2 which reproduces overworld.
  for the creators, it would be good to make a dimension 5, total air without structure,
  to be able to add for example minigame,
  or like me terraforming hub etc.
  I know it's not easy, but to see the rapid evolution of the mod, I think it's a challenge that may interest you

sorry for my english, i'm french translated by google

**Comment by qouteall** [comment]
Adding a void dimension is easy. You said that you need the void dimension for "minigames or terraforming hub". What is terraforming hub?

**Comment by qouteall** [comment]
I add alternate dimensions for connecting above overworld. If you want to make a minigame you can clear an area and it doesn't need to be in a new dimension.

**Comment by qouteall** [comment]
But void dimension may have other uses. I am considering adding it.

**Comment by DjTylerD** [comment]
what I mean by terraforming, it is of type "worldedit", "worldpainter" I update my old server stopped in 1.12, my hub is a floating island with several portals of the world:
"adventure, Redstone tutorial flatmap, pixelart flatmap, flat build, command block ktp-taupegun (which I have to redo in 1.15), and several minigames"

Currently my technique is to teleport to alternate1, load 32 sections, close the map created another map at the same coordinate in flatmap air, do my constructions, close the map replace the folder "region" of alternate1 with the flatmap air that I just created and finally I create the portals

see public video photo album: [](https://www.facebook.com/profile.php?id=100008779717929&sk=media_set&set=a.1591544197814889&type=3)

**Comment by qouteall** [comment]
Alternate 5 was added in the newest version for 1.15
