### ISSUE TITLE
Compatibility issue with NEAT / Mine and Slash

### ISSUE THREAD

**Issue by maldiablo** [qouteall/ImmersivePortalsModForForge#28]
Experiencing this issue using the 1.14.4 version of the mod - immersive-portals-0.14(for mc 1.14 with forge).jar and MixinBootstrap-1.0.1.jar

The issue is that there is a hud that's supposed to appear over mobs heads when using the following mod:  https://www.curseforge.com/minecraft/mc-mods/neat

When IP is installed, the info above enemy heads doesn't render.  

There's another post regarding huds missing from Mine and Slash (https://github.com/qouteall/ImmersivePortalsModForForge/issues/6).  Mine and Slash contains a port of NEAT that pretty much has the same exact issue.  You can probably consolidate that post into this one.

Tested with Forge 1.14.4-28.1.111 and 1.14.4-28.1.113
Testing done with all mods except IP and NEAT just to rule out other mods interfering.

**Comment by qouteall** [comment]
I teseted it with neat in dev environment and the gui shows normally

**Comment by qouteall** [comment]
But mine and slash's gui does not show up

**Comment by qouteall** [comment]
Neat 1.5-19 with Forge 28.1.114 and ip 0.14 works fine

**Comment by qouteall** [comment]
compatibiltiy with mine and slash fixed. it will be in the next version
