### ISSUE TITLE
Immersive Portals Graphics Bug

### ISSUE THREAD

**Issue by Vatruvius** [qouteall/ImmersivePortalsModForForge#289]
Hello,

I have been putting together a modpack for a local server with some friends and I have just finished all my testing and configuration when I ran into this graphical bug with Immersive Portals. I am using Immersive Portals 0.16 for Forge 1.16.5 along with Optifine 1.16.5 HD U G7 on Forge 36.2.0. Based on the notes and warnings on the CurseForge page, Immersive Portals is compatible with this combination.

The specific issue has to do with the nether portal in particular. When a nether portal is created there is a sort of skybox applied to the portal plane based on the nether generation. This skybox is drawn over the player's camera if the player walks through the portal. Depending where you are looking the effect is minimal or obstructive if not disorienting. Only by walking back through the nether portal is the skybox removed from the player's camera and back on the portal's plane. Attached are pictures showing the effect.

This issue makes the nether unplayable and I am curious what could be causing it considering the fact that Optifine HD U G7 is compatible with Immersive Portals for Minecraft 1.16.5. I do have shaders enabled, specifically Sildur's Vibrant Shaders v1.29 with volumetric lighting. What is really curious is that this graphical bug only effects the nether portal and not the end portal.

I hope we can resolve this issue given that compatibility between Immersive Portals, Forge, and Optifine is not very high and a small graphical issue on the only compatible combination of mods ruins the only Immersive Portals experience Forge and Optifine users get to have. Let me know if you want any more details to diagnosis and resolve this particular issue.

Vatruivuis

![Plane_Skybox_1](https://user-images.githubusercontent.com/44359446/131233237-3af97476-50eb-4dbf-94bf-4c588b91c073.png)

![Plane_Skybox_2](https://user-images.githubusercontent.com/44359446/131233257-4b249afd-9593-42f5-a5d8-47b6106191c7.png)

![Plane_Skybox_3](https://user-images.githubusercontent.com/44359446/131233278-3bba1c7d-ab8b-4512-b28f-b5ef93349633.png)

![Plane_Skybox_4](https://user-images.githubusercontent.com/44359446/131233289-938be0e8-9439-4988-9fe3-149ee899c023.png)

![Player_Skybox_1](https://user-images.githubusercontent.com/44359446/131233307-ead89a2b-b697-4beb-a706-4b5c385929b9.png)

![Player_Skybox_2](https://user-images.githubusercontent.com/44359446/131233320-f4aee634-3c1c-4145-807d-5bdd5be99c09.png)

**Comment by Vatruvius** [comment]
After doing some more testing I have discovered that this issue is probably shader pack specific. Since this modpack is for my friends I have varying levels of sharder packs to accommodate everyone regardless of their hardware. Among Sildur's Vibrant Shaders there is Extreme with Volumetric Lighting, Extreme, High, Medium, and Lite. Sildur's Vibrant Shaders Lite is the only shader pack that does not experience this graphical bug. Neither does Optifine's internal shading or if shading is disabled altogether. I'll close this report considering that the issue is with the shaders I use and not the mod specifically.

**Comment by Vatruvius** [comment]
After talking with some shader pack authors and moderators the issue turned out to be the shader pack's bloom setting. If anyone experiences a graphical issue similar to this one try disabling bloom in the shader pack.

**Comment by qouteall** [comment]
It seems to be a framebuffer resolution mismatch issue. You can try to use Iris in 1.17.1 fabric and see whether the issue still occurs https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1 (Iris does not work with all shaders)
