### ISSUE TITLE
Error if I play without the mod! [1.16.5]

### ISSUE THREAD

**Issue by Gazer10** [qouteall/ImmersivePortalsModForForge#291]
Hi, I downloaded the Immersive portals mod for me and my brother's LAN multiplayer world. After playing with it for a bit (activating portals) I decided to delete it. After we both got rid of it, I opened the world just fine, but when my brother tried to join, he got "Could not synchronize registry data with server". We then redownloaded the mod and he was able to join just fine, the problem is that I don't want it because I need Optifine G8 (which the mod doesn't currently support). (Note: This problem only happens in worlds where the mod was previously used.)

Thanks in advance.

**Comment by qouteall** [comment]
It's an issue related to Forge's registry system. There are two ways to solve this
1. use vanilla (not forge) to open the world once.
2. recreate another world with the same seed and configuration, then use the new `level.dat` file to replace the old world's `level.dat`

**Comment by Gazer10** [comment]
Thank you, first way worked flawlessly!
