### ISSUE TITLE
Player loses Player Capability on Dimension Change

### ISSUE THREAD

**Issue by Tsunder** [qouteall/ImmersivePortalsModForForge#3]
playing with "Mine and Slash reloaded" and "corail's tombstone", both mods break after passing through a nether portal, until the player reconnects.

McRobertx22 from Mine and Slash discord suggests "its probably deleting capabilities on dimension change"

**Comment by WenXin20** [comment]
I also found out this affects the [Sol Carrot](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition) mod, food looses it's saved data and then freezes the game.

**Comment by qouteall** [comment]
ok, probably fixed

**Comment by qouteall** [comment]
check 1.14-7 version

**Comment by juliand665** [comment]
@WenXin20 can you test? I'd really appreciate it :)

**Comment by WenXin20** [comment]
As far as I can tell, it is working.
