### ISSUE TITLE
[IMPORTANT!] [1.16.5] Please update this to make it compatible with the latest version of Forge!

### ISSUE THREAD

**Issue by bauerbach** [qouteall/ImmersivePortalsModForForge#303]
The latest version of Minecraft Forge 1.16.5 fixes a critical security vulnerability (see: https://www.minecraft.net/article/important-message--security-vulnerability-java-edition?ref=launcher). However, this mod does not work with the latest version, and it is a critical mod that is needed for my Minecraft server, which means I need to use a version of Forge that has this vulnerability! The server is currently running on localhost, but I am probably going to want to let other players on it eventually!

**Comment by qouteall** [comment]
~~You can add `-Dlog4j2.formatMsgNoLookups=true` to the Java/JVM arguments before `-jar`~~

**Comment by qouteall** [comment]
Sorry, that doesn't work for 1.16

**Comment by qouteall** [comment]
The latest version https://github.com/qouteall/ImmersivePortalsModForForge/releases/tag/v0.17-1.16
should work with the latest forge. (If not, reopen the issue)
