### ISSUE TITLE
update it plz

### ISSUE THREAD

**Issue by james-loves-coding-games1234** [qouteall/ImmersivePortalsModForForge#314]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by james-loves-coding-games1234** [comment]
plz

plz

plz

**Comment by ImSpaceLover** [comment]
No

**Comment by james-loves-coding-games1234** [comment]
i made this account JUST so i can say this so PLZ JUST UPDATE IT i need it for my 1.18 forge backrooms map I've been working on for 473 days (no im not kidding and yes that is more than a year)  and i cant go back and its the only forge portal mod i can find that can do the things yours can like one way portals and such so if you can just do that A HELL OF A LOT OF PEOPLE will be very happy btw fabric is good but i already used forge when starting this map as a fellow coder i understand how annoying it can be to have to make a butt-ton of code just so people can use it for a platform you don't even use anymore but you cant let that stop you i let it stop me and my team once and it was NOT fun so just plz update the mod bro it dose not work to make two of the same mods on different modding platforms and then leave the first one in the dust like that so just think about is plz

**Comment by james-loves-coding-games1234** [comment]
shucks

**Comment by james-loves-coding-games1234** [comment]
nvm

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/#why-is-the-forge-version-not-being-supported
