### ISSUE TITLE
 /portal set_portal_nbt {unbreakable:1b} not working on mirrors

### ISSUE THREAD

**Issue by masterblaster221** [qouteall/ImmersivePortalsModForForge#33]
its weird  when I break the Glass on the  mirror the portal disappears. Also I love Your mod. your a amazing java programmer I have worked in java for 5 years I can't wait to see how far your skill goes.

**Comment by qouteall** [comment]
The unbreakable tag is only for nether portal. But I'm considering making that for mirrors.
