### ISSUE TITLE
[Bug?][1.14.4] Can't See Through the Portal

### ISSUE THREAD

**Issue by JellyJYSK** [qouteall/ImmersivePortalsModForForge#34]
Minecraft Version: 1.14.4
Mod Version: immersive-portals-0.15
Forge Version: 28.2.0

I'm not sure why, but my portals just look like this.
![2020-02-16_12 53 37](https://user-images.githubusercontent.com/54335787/74609784-69103e00-50bb-11ea-949c-da0136d95381.png)
![2020-02-16_12 53 40](https://user-images.githubusercontent.com/54335787/74609785-6c0b2e80-50bb-11ea-8cc2-8739bb8040ca.png)

I am using shaders with optifine if that matters. Im using Sildurs Vibrant Shaders v1.22 medium. 
Optifine HD U F5

**Comment by qouteall** [comment]
1. Try to use another shader
2. If method 1 does not work, try to run command /immersive_portals_debug render_mode_compatibility
3. If that still does not work, run command /immersive_portals_debug gl_check_error_enable
then close the game and show the log file

**Comment by JellyJYSK** [comment]
@qouteall 
You beautiful person you. Thank you so much <3 
Method 2 worked perfectly.

**Comment by qouteall** [comment]
Go to .minecraft/config/immersive_portals-client.toml and change compatibility_render_mode to true then you don't need to use command every time.
