### ISSUE TITLE
cause crash when using with some of MixinBootstrap mods

### ISSUE THREAD

**Issue by MilkissWhite** [qouteall/ImmersivePortalsModForForge#38]
for example, immersive portal mod + water erosion mod will crash at FML early loading progress.
I asked to MixinBootstrap github, and here is answer
----
The first issue with water-erosion and immersive-portals crashing super early is due to both of these mods naming their refmap files main.refmap.json, These files overwrite each other and as a result it can cause the Mixin mappings to go missing. The developers of theses mods should be naming their refmap so they are unique, this is as simple as putting the mod id in the file name.
---
in this time, it can be fix even you do nothing if water-erosion mod change name of main.refmap.json, but I suggest also change name of main.refmap.json in immersive-portals because I think this case will be happen again easilly whenever someone release a mod that using mixinbootstrap.
here is link to LXGaming's comment

https://github.com/13rac1/Minecraft-Water-Erosion/issues/10#issuecomment-587436538

thx for reading and cool mod.

**Comment by qouteall** [comment]
ok I will change refmap name to avoid conflict

**Comment by 13rac1** [comment]
I'm doing the same for water-erosion right now. Edit: Done.
