### ISSUE TITLE
Breaks forge support for allowing other blocks as nether portal frames

### ISSUE THREAD

**Issue by pupnewfster** [qouteall/ImmersivePortalsModForForge#47]
Forge: 31.1.19
Immersive portals (for forge): 0.6

When I was trying to test this mod, and I decided to use refined obsidian blocks (from Mekanism), for the portal frame, but nothing happened. I then tried regular obsidian and it did properly make a portal appear. A while back I made a PR to forge, https://github.com/MinecraftForge/MinecraftForge/pull/6389 to add support for allowing mods to add  support for their custom blocks to be supported as portal frames. It seems like this mod is breaking that feature. I would consider this a bug, which is why I opened this separately from #32

**Comment by qouteall** [comment]
It's not bug. It's feature.

**Comment by qouteall** [comment]
If you want it to support that you can make a pr to this mod.

**Comment by qouteall** [comment]
Sorry I didn't mean to offend you. I am just not interested in implementing it.

**Comment by pupnewfster** [comment]
May I ask what is hard about implementing this feature if you are familiar with the code base and how mixins work (given from my understanding this project uses them). Given all that should be required is changing checking against Blocks.OBSIDIAN to checking `isPortalFrame` on the block you are currently checking for obsidian?

The main reason I am not really interested in implementing this is I don't have the time to look into how mixins work in order to actually setup and test the changes.

**Comment by qouteall** [comment]
implemented. it will be in the next version
