### ISSUE TITLE
Crash after activating nether portal

### ISSUE THREAD

**Issue by DatrixTHLK** [qouteall/ImmersivePortalsModForForge#48]
Hi there.

It would appear that this mod has crashed after activating (or re-activating in my case) a nether portal. 

Minecraft 1.15.2
forge: 31.1.18
MixinBootstrap: 1.0.2
Immersive Portals: 0.6(for mc 1.15 forge)
Crash Log: https://gist.github.com/DatrixTHLK/33dbc9517245eeff640b59f4339bdd06

**Comment by qouteall** [comment]
That crash happens inside Look At That mod.

**Comment by DatrixTHLK** [comment]
I see I will pass this over to the dev of that mod. Thanks for the response!
