### ISSUE TITLE
[1.15.2]The server got stuck when it started

### ISSUE THREAD

**Issue by EnterFor** [qouteall/ImmersivePortalsModForForge#52]
debug.log：https://paste.ubuntu.com/p/TZYcxSF4Ny/

When I install startup, it gets stuck
When I deleted it, it was still stuck.
It's urgent!!

**Comment by qouteall** [comment]
What do you mean "stuck"? Also show the client log.

**Comment by qouteall** [comment]
I need to know which specific mod it's incompatible with. Try to remove half of mods and try again (backup the world)

**Comment by EnterFor** [comment]
I tested it for a long time, and when I removed Mekanism, I was able to enter the game
It's urgent. I don't know whose problem it is

**Comment by EnterFor** [comment]
https://github.com/mekanism/Mekanism/issues/5969

**Comment by EnterFor** [comment]
I am very sorry, this may be the problem of Mekanism
