### ISSUE TITLE
Encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by stanlexgreenson** [qouteall/ImmersivePortalsModForForge#54]
![imagen](https://user-images.githubusercontent.com/60622498/76749620-280b5800-6753-11ea-8d2c-98b732193503.png)

I didn't know if should have posted this in the cursepage comment section or here... Here is the log https://pastebin.com/aXvQUUfg

Minecraft version 1.15.2 forge 31.1.18
Mod version 0.7

**Comment by qouteall** [comment]
Did you install MixinBootstrap

**Comment by stanlexgreenson** [comment]
Omg I'm sorry, I blinded myself. Thanks now it works
