### ISSUE TITLE
1.14.4 Lighting bugs during movement with SEUS shaders (E12)

### ISSUE THREAD

**Issue by Alaberti** [qouteall/ImmersivePortalsModForForge#60]
forge-1.14.4-28.2.0
Immersive-portals-0.15(for+mc+1.14+with+forge)
MixinBootstrap-1.0.2
OptiFine_1.14.4_HD_U_F5
SEUS Shaders E12 (path-tracing on)
[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4385039/latest.log)
[SEUS PTGI E12.zip](https://github.com/qouteall/ImmersivePortalsModForForge/files/4385045/SEUS.PTGI.E12.zip) (shaders)
[SEUS PTGI E12.zip.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4385046/SEUS.PTGI.E12.zip.txt) (shader config)
[optionsof.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4385047/optionsof.txt) (optifine config)

Having an odd issue where, when using this mod and SEUS shaders, lighting sources lose their ambiance as I move.. After passing through a nether portal, the see-through bit works for a while but then everything goes a bit...technicolor? I tried enabling compatibility mode but doesn't seem to help. I'll try to demonstrate with the following screenshots what it looks like:
![2020-03-25_23 34 28](https://user-images.githubusercontent.com/10929796/77610882-eb2d2700-6ef1-11ea-8203-a7c360657ef8.png)

![2020-03-25_23 34 33](https://user-images.githubusercontent.com/10929796/77610885-ed8f8100-6ef1-11ea-8415-9ec9c1f0740f.png)

![2020-03-25_23 34 38](https://user-images.githubusercontent.com/10929796/77610904-f2eccb80-6ef1-11ea-88ae-53587f4a508a.png)

![2020-03-25_23 34 41](https://user-images.githubusercontent.com/10929796/77611095-70184080-6ef2-11ea-96c9-4b7e60ffca41.png)

![2020-03-25_23 50 23](https://user-images.githubusercontent.com/10929796/77611537-95f21500-6ef3-11ea-81f5-fb8a35bec836.png)

![2020-03-25_23 51 05](https://user-images.githubusercontent.com/10929796/77611540-97bbd880-6ef3-11ea-85fb-a1a7355a4212.png)

![2020-03-25_23 50 22](https://user-images.githubusercontent.com/10929796/77611532-91c5f780-6ef3-11ea-9dab-a03c04eeebb5.png)

I appreciate any assistance you can provide, and uh good luck.

**Comment by qouteall** [comment]
This mod is not compatible with path tracing shader as mentioned in mod page.

**Comment by qouteall** [comment]
You can try to use normal shaders.
