### ISSUE TITLE
[1.15.2] Fail to load the game with version 0.8

### ISSUE THREAD

**Issue by Insane96** [qouteall/ImmersivePortalsModForForge#61]
Mod version: 0.8
Forge: 31.1.27

Log: https://gist.github.com/Insane96/d044515b20252d0dee1b3e638ebc879f

**Comment by qouteall** [comment]
Install MixinBootstrap

**Comment by Insane96** [comment]
Why isn't it set as a Dependency

**Comment by qouteall** [comment]
Because MixinBootstrap is not a normal mod.

**Comment by Insane96** [comment]
Btw yep, it worked
