### ISSUE TITLE
[1.15.2] Incompatible with OptiFine

### ISSUE THREAD

**Issue by RobinVanCauter** [qouteall/ImmersivePortalsModForForge#63]
I'm running the Valhesia 2 modpack in combination with the latest optifine preview (1.15.2, pre10) and OptiForge to make it compatible with Forge.

Not sure if this is an issue with OptiFine, OptiForge or ImmersivePortals, but I thought I'd at least ping you about the issue as almost all of the 100+ mods in the modpack are working without issue. (Structurize their compat layer was breaking to due to an error on their side)

Seems like it's breaking on some of the mixins.

Here's the logs: https://pastebin.com/kUrsETmb

Thanks for this awesome mod btw! Great work! :+1:

**Comment by qouteall** [comment]
Just know that there is OptiForge and MixinLoader which is similar to MixinBootstrap.
I am going to fix this issue by myself. Because this mod's shader compatibility is an ugly hack.

**Comment by qouteall** [comment]
Actually the whole mod is ugly hack-_-

**Comment by qouteall** [comment]
fixed in the latest version

**Comment by RobinVanCauter** [comment]
Wow, that was fast, good job! :D

**Comment by T-Grave** [comment]
@qouteall I still got a mixin apply error while booting up
