### ISSUE TITLE
[1.15.2] Build fails

### ISSUE THREAD

**Issue by RobinVanCauter** [qouteall/ImmersivePortalsModForForge#64]
I'm trying to build your mod myself, so I can tinker around with OptiFine support. I followed your instructions as per the README: I ran `gradlew genIntellijRuns` to setup my environment.

But I'm running into the following build error;

 `error: cannot find symbol GeometryPortalShape` inside the Portal.java file.

Any idea why this might be happening? Looks to me like certain files aren't committed? Since I don't see any specific import for it, I expect it's supposed to be in the same package as Portal.java?

**Comment by qouteall** [comment]
The missing files were added
