### ISSUE TITLE
Minecarts and boats lose their content (and momentum)

### ISSUE THREAD

**Issue by Tander** [qouteall/ImmersivePortalsModForForge#65]
immersive-portals-0.9(forMc1.15withForge)

Minecarts and boats (and probably similar entities) loses carried enitites, and minecart with chest loses contained items while crossing portal. Momentum is also resetting, what makes railroads through portals unreliable.

**Comment by qouteall** [comment]
fixed in the latest version

**Comment by Tander** [comment]
Resetting entities is fixed, but because cart is teleported inside portal block, it sticks inside instead of keep moving onto rails (left track on the screenshot). Gladly, right variant seems work more or less reliable, so i'd say it's minor problem.

![изображение](https://user-images.githubusercontent.com/1059805/78018351-665d6580-7356-11ea-9d69-0f86baa4bec9.png)
