### ISSUE TITLE
Crash w/ Pokecube AIO

### ISSUE THREAD

**Issue by WenXin20** [qouteall/ImmersivePortalsModForForge#7]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Immersive Portals v7`
[`Pokecube AIO v2.0.0.c`](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)

I got this crash when a portal was nearby. I assumed a pokemob had entered the portal when the crash occurred. I'm not sure which mod is at fault though.
[Crash Report](https://gist.github.com/WenXin20/36087e629ec006fe6ef944dc805a9ce3)

**Comment by qouteall** [comment]
1.14-8 version may have fixed this but I am not sure.

**Comment by WenXin20** [comment]
Thanks, I'll test it out.

**Comment by WenXin20** [comment]
It still crashes unfortunately.

**Comment by WenXin20** [comment]
It works, thanks!
