### ISSUE TITLE
[1.15] Encounts error when loading

### ISSUE THREAD

**Issue by 11Rick23** [qouteall/ImmersivePortalsModForForge#75]
I can't use this mod for some reason...

I can open Minecraft but Forge simply gives me errors every single time... Can someone help me?

By the way, it doesn't work even when I have only this mod in the mods folder. I'm using the latest version.

Full Error Text:
Immersive Portals (immersive_portals) encountered an error during the load_registries event phase

latest.log: http://simp.ly/publish/4Gr3Wx

**Comment by 11Rick23** [comment]
I'm very looking forward to playing with this mod, please help me!

**Comment by qouteall** [comment]
Did you install MixinBootstrap?

**Comment by 11Rick23** [comment]
...I'm the stupidest person in the world... I forgot!
and it does work with it... sorry, and thanks!
