### ISSUE TITLE
Item and text display bug when looking at portals

### ISSUE THREAD

**Issue by Dummloch58** [qouteall/ImmersivePortalsModForForge#76]
Using Silders Vibrant Shaders v1,23 Extreme with optifine 1.15.2. Whenever looking at a portal all items displays and in game text turns white (Purple/red in the nether when looking at a portal). Doesn't affect visuals of item in hand. I only tested with nether portal.
I changed a variety of shader settings and nothing seemed to affect it. also disabled a variety of potentially afflicting mods and no change

**Comment by Dummloch58** [comment]
![Capture](https://user-images.githubusercontent.com/63926261/79668021-67bec880-8173-11ea-9c6f-e578fcb4c763.PNG)

**Comment by qouteall** [comment]
fixed
