### ISSUE TITLE
Void Under Immersive Portals Dimensions

### ISSUE THREAD

**Issue by ChrisLTheNerd** [qouteall/ImmersivePortalsModForForge#79]
After I stack immersive portal's Alternate2 dimension I can fly up to the dimension normally, but when I fall out of the Alternate2 I die. Also nothing is visible when you look down, the bottom of Alternate2 just turns into the void (top video). When you stack vanilla dimensions like the end, it works completely fine, you can just fall from the end, and into the Over World or Alternate2 (bottom video).  

![ezgif com-optimize (7)](https://user-images.githubusercontent.com/50182206/79710582-6ab0da80-8293-11ea-852b-fbf1bcde166d.gif)

![ezgif com-optimize (8)](https://user-images.githubusercontent.com/50182206/79710971-908aaf00-8294-11ea-8ee8-8742340f94da.gif)

**Comment by qouteall** [comment]
Did you include alternate2 in the dimension stack menu?
And try to first go to alternate2 and then quit to the main menu then enter world again and check does the bottom portal show up

**Comment by Kelton27** [comment]
what I did to fix that is I just connected the dimensions properly by using, for example, to fix your problem "/portal connect_floor minecraft:alternate_dimension_2 minecraft:overworld" which will make it so you can enter the overworld from alternate dimension 2.

**Comment by qouteall** [comment]
It turns out to be caused by forge's strange dimension unloading mechanic
