### ISSUE TITLE
You cannot join a dedicated server

### ISSUE THREAD

**Issue by Lice2** [qouteall/ImmersivePortalsModForForge#8]
MineCraft 1.14.4
Forge : 28.1.111
MixinBootstrap-1.0.0.jar, immersive-portals-1.14-1 (forge) .jar are on the server and on the client in the mod folder

Please check times.
Greetings Lice
p.s. There is no crash or anything, you just can't connect to the server

**Comment by qouteall** [comment]
the mod version should be as same as the server's mod version

**Comment by Lice2** [comment]
Hi, the versions are the same!

**Comment by qouteall** [comment]
the server's mod version is too old. tell the server manager to upgrade

**Comment by Lice2** [comment]
I just updated the server 1 to 1.
its my server

**Comment by Lice2** [comment]
Please don't be angry, but I've been doing this for a few years now and I think your work is really great. But on the server and client are the same versions on it

**Comment by Lice2** [comment]
Please do not be angry. I would like to use your mod on my server.

**Comment by qouteall** [comment]
1 is not the newwst

**Comment by Lice2** [comment]
MixinBootstrap-1.0.0.jar not the newest ?

**Comment by qouteall** [comment]
this mod is called immersive portals not mixinbootstrap

**Comment by Lice2** [comment]
his mod depends on MixinBootstrap: https://github.com/LXGaming/MixinBootstrap/releases/download/v1.0.0/MixinBootstrap-1.0.0.jar

**Comment by Lice2** [comment]
Sorry i am german !

I understood that I need it for that

**Comment by Lice2** [comment]
Without MixinBootstrap-1.0.0 the server crashes
https://pastebin.com/ykANNXXt

**Comment by Lice2** [comment]
Please have a look

**Comment by qouteall** [comment]
it needs mixinbootstrap

**Comment by qouteall** [comment]
put mixinbootstrap into mods folder and put the newest version of this mod into mods folder

**Comment by Lice2** [comment]
i cant connect

**Comment by Lice2** [comment]
test it please

**Comment by Lice2** [comment]
I don't think it's a good thing that you just treat me like I'm nothing.
Check it out, please

**Comment by qouteall** [comment]
delete 1.14-1 version and download 1.14-8 version and put it into mods folder. then put mixinbootstrap into mods folder. am i clear?

**Comment by Lice2** [comment]
I will test, I will now go to bed, I will report ....

**Comment by qouteall** [comment]
I think that the version scheme is a little bit confusing. I will change it in later versions.

**Comment by Lice2** [comment]
Hi, please don't be mad at me, I rebuilt my system after a crash and accidentally started Minecraft from my backup folder.
Please do not be angry with me. I have now set up the server again because there are just too many new mods out there. And yours is there and seems to be going really well.
Greetings Lice

**Comment by Lice2** [comment]
That has never happened to me. Sorry!
