### ISSUE TITLE
Transparent objects overwrite nested portals

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsModForForge#82]
![image](https://user-images.githubusercontent.com/4723091/79879092-1d239300-83a3-11ea-99df-338fa1524c74.png)
see the stained glass overwrites the portal or something

**Comment by LoganDark** [comment]
whoops this should have been opened under non forge repo

**Comment by qouteall** [comment]
test

**Comment by qouteall** [comment]
fixed
