### ISSUE TITLE
new forge version 0.14 seems mega broken

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsModForForge#83]
yes im happy you added move_portal but set_portal_rotation and set_portal_destination are glitchy and cause bunches of bugs now

right now, setting the destination just prints this to chat

![image](https://user-images.githubusercontent.com/4723091/79929754-7cad8d00-83fb-11ea-9d4e-52b389edd7bc.png)

and the portal doesn't visually update, and doesn't even take you to the destination if you walk through it

setting the rotation doesn't update the portal either, but it causes weird issues with complete_bi_way_portal and collisions that can't be fixed unless you delete all portals and recreate them

everything I'm doing worked perfectly fine with 0.13

**Comment by LoganDark** [comment]
so the NBT actually updates (confirmed with `/portal set_portal_nbt {}`) but it requires me to rejoin the world before I can see the changes to the portal, which is dumb

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/79931072-ec714700-83fe-11ea-9f7e-fd77031a9c3b.png)

**Comment by LoganDark** [comment]
taking the portal out of render distance also updates it, so I think this is just the portal not updating when its nbt changes?

**Comment by qouteall** [comment]
oh, the forge version is remapped from the fabric version. I tested it in fabric but not in forge.

**Comment by LoganDark** [comment]
btw while you're doing that could you try slipping in a quick fix for https://github.com/qouteall/ImmersivePortalsMod/issues/167 ? it's really annoying

**Comment by qouteall** [comment]
fixed in 0.15
