### ISSUE TITLE
Stacking Dimensions breaks Mekanism Pipe Renders

### ISSUE THREAD

**Issue by RedFox071** [qouteall/ImmersivePortalsModForForge#84]
I used the connect_ceiling and connect_floor commands to stack the Alternate 2 dimension on the Overworld dimension. If I fly up and then back down the render on the Mekanism pipes breaks. I am able to fix it by removing the connections and then logging out and back in. But the problem repeats if I try again so it is fairly reproducible. 

![2020-04-23_11 48 45](https://user-images.githubusercontent.com/10158857/80135034-9e2e8600-856d-11ea-80f8-934201581432.png)
![2020-04-23_11 51 00](https://user-images.githubusercontent.com/10158857/80135037-9ec71c80-856d-11ea-8364-491dc0fedfe3.png)

**Comment by qouteall** [comment]
Make a block update nearby and it will return to normal

**Comment by qouteall** [comment]
This issue is related to forge model data system's weird design. Radically fixing it will hurt FPS significantly.

**Comment by RedFox071** [comment]
Doesn't seem to do it for me. If I replace a pipe all the ones in the chain go back to normal but only for a couple of minutes at most.
