### ISSUE TITLE
ImmersivePortals Stuck On Black Screen Everytime World Loaded

### ISSUE THREAD

**Issue by OminousOCE** [qouteall/ImmersivePortalsModForForge#88]
Hello, I am hoping for some possible help here. 

Not entirely sure where the error is coming from, could be incompatibility from others mods. So i apologize if this isnt a concern for the creator.

I have tried to use this mod a few times over the past month or two and everytime i create a new world/load an existing one with this mod, my screen is forever black.. I can see myself moving on my Map and hear in game movements.

I have to remove the mod and continue playing without out it, which i would rather not do as this looks awesome. 

I know this information isnt alot to help with so please let me know what/if any Logs can be provided to help narrow down the issue?. 

My game doesnt crash, so i would only be able to provide any other log.

Thanks!

**Comment by LoganDark** [comment]
> everytime i create a new world/load an existing one with this mod, my screen is forever black..

Could you give me a screenshot of your f3 screen when your screen is black?

**Comment by OminousOCE** [comment]
Dude i am so confused and i apologize for wasting your time here.

I literally have been trying to get it too work for over an hour by removing mods etc, and after i post here and i go to load the world and get a screenshot, i can actually see in game??

I have just tested it multiple times and on a few worlds and it seems i am no longer having black screens now?

Lol so weird it fixes right after i post, this can be closed now, sorry for that & thanks for the quick reply!
