### ISSUE TITLE
Licensing Information is Incorrect

### ISSUE THREAD

**Issue by Gamebuster19901** [qouteall/ImmersivePortalsModForForge#9]
The licensing information on curseforge for this mod is incorrect. It states that it's "All Rights Reserved". But this repository is licensed under MIT.

![image](https://user-images.githubusercontent.com/7155747/72201401-91a07a80-3421-11ea-9e04-e330bb8d0f41.png)
![image](https://user-images.githubusercontent.com/7155747/72201411-ae3cb280-3421-11ea-946e-c5374942b52f.png)

**Comment by qouteall** [comment]
ok. corrected.
