### ISSUE TITLE
Forge having issues with this mod.

### ISSUE THREAD

**Issue by Poseidon05h** [qouteall/ImmersivePortalsModForForge#95]
At the time of writing this I have the latest version of immersive portals and the latest version of forge for 1.15.2. I have no other mods besides immersive portals in my mods folder. Every time I launch minecraft, forge will do it's thing and load everything but right as its about to launch to the minecraft screen it says "Immersive portals encountered an error during the load_registries even phrase". I do not know what to do about this

**Comment by LoganDark** [comment]
Install MixinBootstrap.

https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap
