### ISSUE TITLE
Add a GUI if MixinBootstrap is not installed

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsModForForge#96]

**Comment by LoganDark** [comment]
Or throw a custom exception, since people are clearly smart enough to know how to read the first line of a crash report, but not much more.

**Comment by LoganDark** [comment]
You could also simply specify MixinBootstrap as a Forge dependency and let Forge's GUI tell the user it's missing.

**Comment by qouteall** [comment]
I cannot make MixinBootstrap as a dependency because it's not a normal mod, it does not contain mods.toml and has no mod id

**Comment by LoganDark** [comment]
Custom solution it is then. Maybe check if some Mixin class exists and throw an exception if not. Class.forName?
