### ISSUE TITLE
Compatibility for version 1.12.2?

### ISSUE THREAD

**Issue by Geezt435** [qouteall/ImmersivePortalsModForForge#97]
I made a private mod pack for my world and most of the mods there are on version 1.12.2, if you could please make It into 1.12.2 I would be very, very grateful. 

Thanks in regard,
- Geezt Jeez

**Comment by LoganDark** [comment]
Sorry, 1.12.2 is an entirely different codebase. You can use BetterPortals for this.

**Comment by rvveber** [comment]
Could you backport this to 1.12.2 please?

Would also be very very grateful.
Because BetterPortals does not nearly support the flexiblity of for example setting the destination world of the portal and making actual non euclidean things :c

**Comment by froyo4u** [comment]
> 
> 
> Could you backport this to 1.12.2 please?
> 
> Would also be very very grateful.
> Because BetterPortals does not nearly support the flexiblity of for example setting the destination world of the portal and making actual non euclidean things :c

Backporting is generally not something that quoteall does, sorry.
